/*
 * Opal Custom App Connector API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
	"fmt"
	"net/http"
	"strconv"

	"github.com/gin-gonic/gin"
	authentik "goauthentik.io/api/v3"
)

type UsersAPI struct {
}

// Post /users
func (api *UsersAPI) CreateUser(c *gin.Context) {
	var createUserRequest CreateUserRequest
	err := c.BindJSON(&createUserRequest)
	if err != nil {
		c.JSON(401, buildRespFromErr(err, 401))
		return
	}

	authentik, err := NewAuthentikClient()
	if err != nil {
		c.JSON(http.StatusInternalServerError, buildRespFromErr(err, http.StatusInternalServerError))
		return
	}

	userRemoteID, err := authentik.CreateUser(c, toAuthentikUserRequest(createUserRequest))
	if err != nil {
		var clientErr *ClientError
		if errors.As(err, &clientErr) {
			c.JSON(clientErr.StatusCode, buildRespFromErr(err, clientErr.StatusCode))
		} else {
			c.JSON(http.StatusInternalServerError, buildRespFromErr(err, http.StatusInternalServerError))
		}
		return
	}

	c.JSON(http.StatusOK, &CreateUserResponse{
		RemoteUserId: *userRemoteID,
	})
}

// Get /users
func (api *UsersAPI) GetUsers(c *gin.Context) {
	authentik, err := NewAuthentikClient()
	if err != nil {
		c.JSON(http.StatusInternalServerError, buildRespFromErr(err, http.StatusInternalServerError))
		return
	}

	authentikUsers, nextCursor, err := authentik.PaginatedListUsers(c)
	if err != nil {
		var clientErr *ClientError
		if errors.As(err, &clientErr) {
			c.JSON(clientErr.StatusCode, buildRespFromErr(err, clientErr.StatusCode))
		} else {
			c.JSON(http.StatusInternalServerError, buildRespFromErr(err, http.StatusInternalServerError))
		}
		return
	}

	users := make([]User, 0)
	for _, authentikUser := range authentikUsers {
		user := toOpalUser(authentikUser)
		if user != nil {
			users = append(users, *user)
		}
	}

	c.JSON(http.StatusOK, &UsersResponse{
		Users:      users,
		NextCursor: &nextCursor,
	})
}

func toOpalUser(user authentik.User) *User {
	if user.GetEmail() == "" {
		return nil
	}

	return &User{
		Id:    strconv.Itoa(int(user.GetPk())),
		Email: user.GetEmail(),
	}
}

func toAuthentikUserRequest(request CreateUserRequest) authentik.UserRequest {
	isActive := true
	email := request.Attributes.Email

	return authentik.UserRequest{
		Username: request.Attributes.Email,
		Name:     fmt.Sprintf("%s %s", request.Attributes.FirstName, request.Attributes.LastName),
		IsActive: &isActive,
		Email:    &email,
	}
}
