/*
 * Opal Custom App Connector API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type ResourcesAPI struct {
}

// Post /resources/:resource_id/users
func (api *ResourcesAPI) AddResourceUser(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /resources/:resource_id
func (api *ResourcesAPI) GetResource(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /resources/:resource_id/access_levels
func (api *ResourcesAPI) GetResourceAccessLevels(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /resources/:resource_id/users
func (api *ResourcesAPI) GetResourceUsers(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /resources
func (api *ResourcesAPI) GetResources(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Delete /resources/:resource_id/users/:user_id
func (api *ResourcesAPI) RemoveResourceUser(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

