/*
 * Opal Custom App Connector API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AddGroupMemberGroupRequest struct {

	// The ID of the member group to add.
	GroupId string `json:"group_id"`

	// The identifier of your custom app.
	AppId string `json:"app_id"`
}
