/*
 * Opal Custom App Connector API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GroupResource struct {

	// The id of the resource in your system. Opal will provide this id when making requests for the resource to your connector.
	ResourceId string `json:"resource_id"`

	AccessLevel AccessLevel `json:"access_level,omitempty"`
}
