/*
 * Opal Custom App Connector API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateUserRequest struct {

	// The ID of the user to create in your custom connector app.
	UserId string `json:"user_id,omitempty"`

	Attributes UserAttributes `json:"attributes,omitempty"`

	Manager UserAttributes `json:"manager,omitempty"`

	// The tags of the user that were ingested by Opal
	UserTags []UserTagAttributes `json:"user_tags,omitempty"`
}
