/*
 * Opal Custom App Connector API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GroupResponse struct {

	// The id of the group in your system. Opal will provide this id when making requests for the group to your connector.
	Id string `json:"id"`

	// The name of the group
	Name string `json:"name"`

	// The description of the group
	Description string `json:"description,omitempty"`
}
