/*
 * Opal Custom App Connector API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AddGroupResourceRequest struct {

	// The id of the resource.
	ResourceId string `json:"resource_id"`

	// The identifier of your custom app.
	AppId string `json:"app_id"`

	// The id of the access level.
	AccessLevelId string `json:"access_level_id,omitempty"`
}
