/*
 * Opal Custom App Connector API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UserTagAttributes struct {

	// The key of the tag in Opal
	Key string `json:"key,omitempty"`

	// The value of the tag in Opal
	Value string `json:"value,omitempty"`

	// The ID of the tag in Opal
	TagId string `json:"tag_id,omitempty"`

	// The ID of the source connection in Opal
	ConnectionId string `json:"connection_id,omitempty"`
}
