/*
 * Opal Custom App Connector API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GroupMemberGroup struct {

	GroupId string `json:"group_id,omitempty"`

	Name string `json:"name,omitempty"`

	Description string `json:"description,omitempty"`
}
