/*
 * Opal Custom App Connector API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateUserResponse struct {

	// The ID of the user in your system. Opal will use this to associate the user with the corresponding Opal user.
	RemoteUserId string `json:"remote_user_id"`
}
