/*
 * Opal Custom App Connector API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UserAttributes struct {

	// The email of the user.
	Email string `json:"email,omitempty"`

	// The first name of the user.
	FirstName string `json:"first_name,omitempty"`

	// The last name of the user.
	LastName string `json:"last_name,omitempty"`

	// The title of the user, if available
	Title string `json:"title,omitempty"`

	// The team of the user, if available
	Team string `json:"team,omitempty"`

	// The URL to the user's profile photo
	ProfileUrl string `json:"profile_url,omitempty"`

	// The secondary emails of the user, if available
	SecondaryEmails []string `json:"secondary_emails,omitempty"`
}
